image: registry.gitlab.com/jrevolt/citools/docker-git:latest

services:
- docker:dind

variables:
  GIT_STRATEGY: none

build:
  stage: build
  script:
  - |
    # checkout sources
    # using custom strategy because of gitversion requirements
    git init . &&
    git remote add origin "$CI_REPOSITORY_URL" &&
    git fetch -t origin &&
    if [ "$CI_COMMIT_TAG" != "" ]; then
      git checkout master && git reset --hard $CI_COMMIT_TAG
    else
      git checkout "$CI_COMMIT_REF_NAME"
    fi
    source .gitlab-ci.sh
  - |
    # prepare docker auth
    docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
    cat /root/.docker/config.json > .git/docker.json
  - |
    # determine image tag
    if [ "$CI_COMMIT_TAG" != "" ]; then
      IMAGE_TAG="$CI_COMMIT_TAG"
    else
      IMAGE_TAG="$CI_COMMIT_REF_SLUG"
    fi
    echo "IMAGE_TAG=$IMAGE_TAG"
  - |
    # run buildkit build
    version=$IMAGE_TAG image
  - |
    # if tagged, publish also as "latest"
    if [[ "${CI_COMMIT_TAG:-}" != "" ]]; then
      src=${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
      dst=${CI_REGISTRY_IMAGE}:latest
      docker pull ${src} &&
      docker tag ${src} ${dst} &&
      docker push ${dst} &&
      echo "DONE: $dst => $src"
    else
      echo "SKIP"
    fi
  - |
    # publish to docker.io (master/tag only)
    if [[ "${CI_COMMIT_TAG:-}" != "" || "${CI_COMMIT_REF_SLUG}" = "master" ]]; then
      src=${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
      dst=docker.io/jrevolt/rook-ceph-backup:${IMAGE_TAG}
      docker pull ${src} &&
      docker tag ${src} ${dst} &&
      docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASSWORD" &&
      docker push ${dst} &&
      echo "DONE: $dst => $src"
    else
      echo "SKIP"
    fi



