---
k8s:

  proxy:
    host:
    port:

  kubectl:
    config: /root/.kube/config

  rancher:
    url:
    accessKey:
    secretKey:

  elasticsearch:
    indexPrefix: #k8s-tools-clustername
    clientOpts:
      host: #https://elasticsearch.mdxdev.sk

  backup:
    nameFormat: YYYYMMDD-HHmm
    namePattern: ^\d{8}-\d{4}$
    path: /mnt/backups
    storageClassName: rook-ceph-block
    pool: rbd
    monthly: { max: 2, .dayOfMonth: 1, .dayOfWeek: Sunday }
    weekly:  { max: 3, dayOfWeek: Sunday }
    daily:   { max: 5 }

  semaphore:
    backup: 5
    operator: 10
    exec: 15

  #deployments:
    #namespace:
      #name:
