---
rbdtools:

  elasticsearch:
    indexPrefix: #k8s-tools-clustername
    clientOpts:
      host: #https://elasticsearch.mdxdev.sk

  backup:
    nameFormat: YYYYMMDD-HHmmss
    namePattern: ^\d{8}-\d{6}$
    path: /backups
    storageClassName: rook-ceph-block
    monthly: { max: 2, .dayOfMonth: 1, .dayOfWeek: Sunday }
    weekly:  { max: 3, dayOfWeek: Sunday }
    daily:   { max: 5 }

  semaphore:
    backup: 5
    operator: 10
    exec: 15

