---
k8s:
  backup:
    path: /mnt/backups/pbetest
    storageClassName: rook-ceph-block
    pool: replicapool
    monthly: { max: 2, dayOfMonth: 1 }
    weekly:  { max: 2, dayOfWeek: Sunday }
    daily:   { max: 5 }

  kubectl:
    config: config/kubectl.local.yaml

  .deployments:
    rook-ceph-backup-test:
      test-deployment:
      test-statefulset:
